#!/usr/bin/env python
"""Predict labels for unlabeled encrypted traffic data using a saved baseline model."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable

import joblib
import numpy as np
import pandas as pd


def _strip_trailing_commas(text: str) -> str:
    return re.sub(r",+\s*$", "", text)


def load_arff(path: Path) -> pd.DataFrame:
    attributes: list[str] = []
    rows: list[list[str | None]] = []
    in_data = False

    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        for raw in handle:
            line = raw.strip()
            if not line or line.startswith("%"):
                continue

            lower = line.lower()
            if not in_data:
                if lower.startswith("@attribute"):
                    cleaned = _strip_trailing_commas(line)
                    match = re.match(
                        r"@attribute\s+('[^']+'|\"[^\"]+\"|[^\s,]+)\s+(.+)$",
                        cleaned,
                        flags=re.IGNORECASE,
                    )
                    if match:
                        attributes.append(match.group(1).strip("'\""))
                elif lower.startswith("@data"):
                    in_data = True
                continue

            cleaned = _strip_trailing_commas(line)
            parts = [part.strip() for part in cleaned.split(",")]
            if len(parts) < len(attributes):
                parts.extend([None] * (len(attributes) - len(parts)))
            elif len(parts) > len(attributes):
                parts = parts[: len(attributes)]
            rows.append(parts)

    if not attributes:
        raise ValueError(f"No attributes parsed from ARFF: {path}")
    if not rows:
        raise ValueError(f"No data rows parsed from ARFF: {path}")

    return pd.DataFrame(rows, columns=attributes)


def load_dataset(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".arff":
        return load_arff(path)
    if suffix == ".csv":
        return pd.read_csv(path)
    raise ValueError(f"Unsupported file type: {suffix}. Use .arff or .csv")


def infer_existing_label(columns: Iterable[str], preferred_label: str | None) -> str | None:
    column_list = list(columns)
    lower_map = {col.lower(): col for col in column_list}
    if preferred_label and preferred_label.lower() in lower_map:
        return lower_map[preferred_label.lower()]
    for candidate in ("class1", "class", "label", "target"):
        if candidate in lower_map:
            return lower_map[candidate]
    return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Predict labels from unlabeled ARFF/CSV data.")
    parser.add_argument("--model", required=True, help="Path to model.joblib generated by train_baseline.py")
    parser.add_argument("--data", required=True, help="Path to unlabeled .arff or .csv dataset")
    parser.add_argument("--label", default=None, help="Optional label column to drop if present")
    parser.add_argument("--output", default="outputs/predictions/predictions.csv", help="Prediction CSV output path")
    args = parser.parse_args()

    model_path = Path(args.model)
    data_path = Path(args.data)
    output_path = Path(args.output)

    if not model_path.exists():
        raise FileNotFoundError(f"Model file not found: {model_path}")
    if not data_path.exists():
        raise FileNotFoundError(f"Dataset file not found: {data_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    bundle = joblib.load(model_path)
    model = bundle["model"]
    feature_columns = bundle["feature_columns"]
    trained_label_column = bundle.get("label_column")

    df = load_dataset(data_path)
    original_df = df.copy()

    existing_label = infer_existing_label(df.columns, args.label or trained_label_column)
    if existing_label and existing_label in df.columns:
        df = df.drop(columns=[existing_label])

    missing_columns = [column for column in feature_columns if column not in df.columns]
    if missing_columns:
        raise ValueError(f"Missing feature columns: {missing_columns}")

    x = df[feature_columns].copy()
    for column in x.columns:
        x[column] = pd.to_numeric(x[column], errors="coerce")
    x = x.replace([np.inf, -np.inf], np.nan)

    predictions = model.predict(x)

    results = original_df.copy()
    results["predicted_label"] = predictions
    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(x)
        results["predicted_confidence"] = probabilities.max(axis=1)

    results.to_csv(output_path, index=False)

    print("Prediction finished.")
    print(f"Samples     : {len(results)}")
    print(f"Model       : {model_path}")
    print(f"Input data  : {data_path}")
    print(f"Output file : {output_path}")


if __name__ == "__main__":
    main()
